'use strict';
// An admin review projection over the existing queue. This module has no publishing transport.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const ROOTS={imali:'/home/opc/imali-sniper/marketing',sports_jedi:'/home/opc/sports-jedi/marketing'};
const PLATFORMS=['facebook','instagram','tiktok','pinterest','youtube','x','linkedin','telegram','threads'];
const url=x=>{try{const u=new URL(x);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}};
const revision=j=>hash({content:j.content,provider_state:j.provider_state,state:j.state,updated_at:j.updated_at});
const creativeUrl=x=>/^\/api\/admin\/social\/center\/assets\/(imali|sports_jedi)\/[A-Za-z0-9_-]+\/(image|video)$/.test(x||'')?x:url(x);
function original(j){const c=j.content||{},p=c.prepared_content||c,s=c.campaign?.source;return {caption:p.caption||p.message||p.text||(Array.isArray(p.frames)?p.frames.join('\n\n'):'')||'',title:p.title||s?.data?.title||'',cta:p.cta||'',destination:url(p.link||p.destination||s?.data?.url),hashtags:p.hashtags||'',creative:creativeUrl(p.media_url||p.image_url||p.video_url),type:p.type||(p.mode==='PROMPT_ONLY'?'Video prompt':'Text'),prompt:p.prompt||'',frames:p.frames||[],campaign:c.campaign?.campaign_id||c.campaign_id||null,topic:s?.data?.title||s?.data?.symbol||c.topic||null,product:c.product_name||(j.brand==='sports_jedi'?'Sports Jedi':j.brand==='founder'?'Founder / personal':'IMALI')};}
function normalize(j){const r=j.provider_state?.review_center||{},post={...original(j),...r.draft};let status;
if(j.state==='POSTED'||r.manual_published)status='PUBLISHED';
else if(j.state==='POSTING')status=j.error||j.provider_state?.step==='REVIEW'?'FAILED':'SCHEDULED';
else if(r.decision==='REJECTED')status='REJECTED';
else if(r.dismissed)status='DRAFTS';
else if(['FAILED','RETRY'].includes(j.state))status='FAILED';
else if(r.scheduled_at||j.state==='SCHEDULED'||(j.state==='APPROVED'&&j.scheduled_at))status='SCHEDULED';
else if(r.decision==='APPROVED'||(!r.history&&j.provider_state?.content_approval)||j.state==='APPROVED')status='APPROVED';
else if(post.caption||post.prompt)status='NEEDS_APPROVAL';else status='DRAFTS';
return {id:j.id,source:'social_queue_v1',brand:j.brand,platform:j.platform,...post,status,backend_state:j.state,created_at:j.created_at,scheduled_at:r.scheduled_at||j.scheduled_at,published_at:r.manual_published?.at||j.published_at,public_url:r.manual_published?.url||j.public_url,platform_post_id:j.platform_post_id,publishing_method:r.manual_published?'MANUAL':j.state==='POSTED'?'AUTOMATIC':null,error:j.error||(j.state==='POSTING'&&j.provider_state?.step==='REVIEW'?'CONFIRMATION_UNKNOWN_DO_NOT_RETRY':null),failure_time:r.last_failure?.at||(['FAILED','RETRY','POSTING'].includes(j.state)?j.updated_at:null),attempts:j.provider_state?.attempts||0,retryable:false,retry_reason:j.state==='POSTING'?'Confirm the external outcome first; do not duplicate this post.':'No enabled automatic publishing workflow for this review item.',capability:'MANUAL POST REQUIRED',reason:'You must publish this post manually. Approval saves your content decision only.',revision:revision(j),automation_preview:!!j.provider_state?.automation_preview,automatic_job:!!j.approved_by&&!j.provider_state?.preparation_only,editable:!['POSTED','POSTING'].includes(j.state)&&!(j.approved_by&&!j.provider_state?.preparation_only&&['APPROVED','SCHEDULED','RETRY'].includes(j.state))&&!r.manual_published,manual_allowed:!['POSTING','APPROVED','SCHEDULED','POSTED'].includes(j.state),review:r,source_timestamp:j.content?.campaign?.source?.timestamp||null};}
function readPackages(roots=ROOTS){const result=[];for(const [brand,root] of Object.entries(roots)){if(!fs.existsSync(root+'/output'))continue;for(const file of fs.readdirSync(root+'/output').filter(x=>/^[A-Za-z0-9_-]+\.json$/.test(x)&&x!=='latest.json')){let p;try{p=JSON.parse(fs.readFileSync(root+'/output/'+file,'utf8'));}catch{continue;}if(!p||Array.isArray(p)||!p.campaign_id)continue;const id=p.campaign_id;if(!/^[A-Za-z0-9_-]+$/.test(id))continue;const created=p.created_at?(/Z$|[+-]\d\d:\d\d$/.test(p.created_at)?p.created_at:p.created_at+'Z'):null;const common={brand,product:p.product_name||(brand==='sports_jedi'?'Sports Jedi':'IMALI'),campaign:id,topic:p.topic||p.matchup||p.title||p.headline,title:p.title||p.headline||'',destination:url(p.tracked_url||p.landing_page),created_at:created,source:'marketing_package',type:'Image',status:'DRAFTS',capability:'MANUAL POST REQUIRED',reason:'Generated copy; no publishing receipt is recorded. Add to review before using it.',editable:false,manual_allowed:false};
const image=p.image_file||path.join(root,'images',id+'.png');const video=p.video_file||path.join(root,'videos',id+'.mp4');
const asset=(file,kind)=>{try{const real=fs.realpathSync(file),base=fs.realpathSync(root);return real.startsWith(base+'/')&&fs.statSync(real).isFile()?{file:real,kind}:null;}catch{return null;}};
const media=asset(image,'image');const creative=media?`/api/admin/social/center/assets/${brand}/${id}/image`:null;
const social=p.social||Object.fromEntries(['telegram','facebook','instagram','x','threads'].filter(k=>p[k]).map(k=>[k,p[k]]));
for(const [platform,caption] of Object.entries(social)){if(!PLATFORMS.includes(platform)||typeof caption!=='string')continue;let publishedDate=null;if(brand==='sports_jedi'&&platform==='telegram'){try{const date=fs.readFileSync(root+'/output/last-published-date.txt','utf8').trim();if(p.created_at?.startsWith(date))publishedDate=date;}catch{}}result.push({...common,id:`legacy:${brand}:${id}:${platform}`,platform,caption,creative,can_import:!publishedDate,_asset:media,...(publishedDate?{status:'PUBLISHED',publishing_method:'AUTOMATIC',published_date:publishedDate,published_at:null,reason:'The existing Sports Jedi publisher saved success for '+publishedDate+'. Exact publish time and external message ID were not retained.'}:{})});}
if(p.youtube_video_id){const v=asset(video,'video');result.push({...common,id:`legacy:${brand}:${id}:youtube`,platform:'youtube',type:'Video',caption:p.seo_description||'',creative:v?`/api/admin/social/center/assets/${brand}/${id}/video`:creative,_asset:v||media,status:'PUBLISHED',publishing_method:'AUTOMATIC',platform_post_id:p.youtube_video_id,public_url:url(p.youtube_url),published_at:p.youtube_uploaded_at||null,reason:'Recorded YouTube upload receipt. Privacy: '+(p.youtube_privacy||'not recorded')+'. Upload time was not saved by the legacy uploader.'});}
} }return result;}
function clean(p){const {_asset,...rest}=p;return rest;}
function createCenter({db,roots=ROOTS,getConfig=()=>require('./connections').loadConfig?.(),facebookConfig=()=>require('./facebook-service').loadConfig(),facebookCheck=()=>require('./facebook-service').createService().connection()}){
let fbCheck={at:0,result:null};
async function connections(rows,library){const c=getConfig()?.c||{};const con=(await db.query('SELECT brand,platform,account_name,connection_status,last_error,token_expiration FROM social_connections_v1 ORDER BY brand,platform')).rows;let fb;try{fb=facebookConfig();}catch{fb={};}
if(fb.token&&fb.pageId&&Date.now()-fbCheck.at>300000){try{fbCheck={at:Date.now(),result:await facebookCheck()};}catch(e){fbCheck={at:Date.now(),result:{error:/^[A-Z_]+$/.test(e.message)?e.message:'FACEBOOK_CONNECTION_CHECK_FAILED'}};}}
return ['imali','sports_jedi','founder'].flatMap(brand=>(brand==='founder'?['instagram','threads']:PLATFORMS).map(platform=>{const x=con.find(x=>x.brand===brand&&x.platform===platform),posts=[...rows,...library].filter(x=>x.brand===brand&&x.platform===platform),success=posts.filter(x=>x.status==='PUBLISHED'),fail=posts.filter(x=>x.error),scheduled=posts.filter(x=>['SCHEDULED','APPROVED'].includes(x.status)&&x.scheduled_at&&new Date(x.scheduled_at)>new Date()).sort((a,b)=>String(a.scheduled_at).localeCompare(String(b.scheduled_at)));let state=x?.connection_status==='CONNECTED'?'CONNECTED':c.apps?.[platform]?.client_id&&c.apps?.[platform]?.client_secret?'CONFIGURED / DISCONNECTED':'NOT CONFIGURED',capability='NOT CONNECTED',reason='No confirmed platform authorization. You must publish this post manually.';
if(brand==='imali'&&platform==='facebook'&&fb.token&&fb.pageId){state=fbCheck.result?.valid?'CONNECTED':'CONNECTED BUT FAILING';capability=fbCheck.result?.valid&&fb.enabled?'AUTO PUBLISH AVAILABLE':'PUBLISHING BLOCKED';reason=fbCheck.result?.error||(fb.enabled?'Facebook publisher is enabled. Prepared review drafts need the dedicated publishing workflow.':'FACEBOOK_PUBLISH_DISABLED');}
else if(brand==='imali'&&platform==='youtube'&&success.length){state='PREVIOUS UPLOADS RECORDED';capability='MANUAL POST REQUIRED';reason='Legacy YouTube uploader exists; AUTO_YOUTUBE=false. Current authorization has not been verified.';}
else if(brand==='sports_jedi'&&platform==='telegram'){let date;try{date=fs.readFileSync(roots.sports_jedi+'/output/last-published-date.txt','utf8').trim();}catch{}state=date?'CONNECTED + WORKING':'NOT CONFIGURED';capability=date?'LEGACY AUTO PUBLISHER':'NOT CONNECTED';reason=date?`Independent daily publisher recorded success on ${date}. Social Center approval does not trigger this service.`:reason;}
else if(state==='CONNECTED'){const runtime=require('./automation').runtimeStatus();const ready=runtime.workers[platform]&&(!x.token_expiration||new Date(x.token_expiration)>new Date());capability=x.last_error?'PUBLISHING BLOCKED':ready?'AUTO PUBLISH AVAILABLE':'PUBLISHING BLOCKED';reason=x.last_error||(ready?'Approved publisher jobs can publish automatically. Review-only drafts remain manual until explicitly submitted through their publishing workflow.':'Publisher worker inactive or token expired.');}
return {brand,platform,connection_status:state,capability,reason,automatic_in_center:false,app_configured:!!(c.apps?.[platform]?.client_id&&c.apps?.[platform]?.client_secret),last_success:success.sort((a,b)=>String(b.published_at||b.created_at||'').localeCompare(String(a.published_at||a.created_at||'')))[0]||null,last_failure:fail.sort((a,b)=>String(b.failure_time).localeCompare(String(a.failure_time)))[0]||null,next_scheduled:scheduled[0]?.scheduled_at||null};}));}
async function snapshot(){const raw=(await db.query('SELECT * FROM social_queue_v1 ORDER BY created_at DESC')).rows;const posts=raw.filter(j=>!j.provider_state?.live_queue_id).map(normalize),library=readPackages(roots);const imported=new Set(raw.map(j=>j.content?.legacy_id).filter(Boolean));const history=library.filter(x=>x.status==='PUBLISHED'&&!imported.has(x.id));const items=[...posts,...history];const counts=Object.fromEntries(['NEEDS_APPROVAL','APPROVED','SCHEDULED','PUBLISHED','FAILED','REJECTED','DRAFTS'].map(s=>[s,items.filter(p=>p.status===s).length]));const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());counts.PUBLISHED_TODAY=items.filter(p=>p.status==='PUBLISHED'&&p.published_at&&new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date(p.published_at))===today).length;
const platforms=await connections(posts,library);for(const x of platforms){for(const key of ['last_success','last_failure']){const p=x[key];if(p)x[key]={id:p.id,published_at:p.published_at,failure_time:p.failure_time,error:p.error,platform_post_id:p.platform_post_id,public_url:p.public_url};}}for(const p of posts){const c=platforms.find(x=>x.platform===p.platform&&x.brand===p.brand);if(p.automation_preview&&c?.capability==='AUTO PUBLISH AVAILABLE'){p.publish_available=true;p.capability=c.capability;p.reason='After approval, choose Post Now and confirm the destination. IMALI will queue this qualified post through the existing publisher.';}if(c?.capability==='PUBLISHING BLOCKED'){p.capability=c.capability;p.reason=c.reason+' You must publish this post manually.';}else if(c?.capability==='NOT CONNECTED'){p.capability='NOT CONNECTED';p.reason=c.reason;}if(p.automatic_job&&['APPROVED','POSTING','SCHEDULED'].includes(p.backend_state)&&!p.error){p.capability='AUTO PUBLISH AVAILABLE';p.reason='This approved job is managed by the platform publisher. Do not post a manual duplicate.';}if(p.backend_state==='POSTING'&&p.error){p.capability='PUBLISHING BLOCKED';p.reason=p.error;}}
return {success:true,as_of:new Date().toISOString(),timezone:'America/New_York',counts,items:items.map(clean),library:library.filter(x=>x.status!=='PUBLISHED'&&!imported.has(x.id)).map(clean),platforms,automatic_publishing:require('./automation').runtimeStatus().automatic_publishing};}
async function change(id,body,actor){if(!/^[a-f0-9-]{36}$/.test(id)||!actor)throw Error('INVALID_REVIEW');const client=await db.connect();try{await client.query('BEGIN');const j=(await client.query('SELECT * FROM social_queue_v1 WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!j)throw Error('POST_NOT_FOUND');if(body.revision!==revision(j))throw Error('POST_CHANGED_REFRESH_REQUIRED');const p=normalize(j);if(!p.editable)throw Error('POST_LOCKED_RECONCILE_EXTERNAL_OUTCOME');const r={...(j.provider_state?.review_center||{})},at=new Date().toISOString();
if(j.error&&!r.last_failure)r.last_failure={at:j.updated_at,error:j.error};
const action=body.action;if(!['approve','reject','edit','regenerate','schedule','manual','dismiss'].includes(action))throw Error('ACTION_NOT_SUPPORTED');
if(action==='edit'){const d=body.draft||{};for(const k of ['caption','title','cta','hashtags']){if(typeof d[k]!=='string'||d[k].length>20000)throw Error('INVALID_POST_TEXT');}for(const k of ['destination','creative'])if(d[k]&&!(k==='creative'?creativeUrl(d[k]):url(d[k])))throw Error('INVALID_POST_URL');r.draft={caption:d.caption,title:d.title,cta:d.cta,hashtags:d.hashtags,destination:url(d.destination),creative:creativeUrl(d.creative)};r.decision=null;r.scheduled_at=null;r.dismissed=false;}
if(action==='regenerate'){if(j.content?.campaign){const c=j.content.campaign;const C=require('/home/opc/imali-sniper/marketing/campaign-content');const jobs=require('/home/opc/imali-sniper/marketing/campaign-orchestrator').preparedJobs(C.buildCampaign(j.brand,c.source,c.slot));const regenerated=jobs.find(x=>x.platform===j.platform&&x.placement===j.content.placement);if(!regenerated)throw Error('SOURCE_REGENERATION_UNAVAILABLE');r.draft=original({...j,content:{...j.content,prepared_content:regenerated.payload}});}else r.draft=null;r.decision=null;r.scheduled_at=null;r.dismissed=false;}
if(['approve','schedule'].includes(action)){if(['FAILED','RETRY'].includes(j.state))throw Error('EDIT_FAILED_POST_BEFORE_APPROVAL');if(!p.caption.trim())throw Error('CAPTION_REQUIRED');r.decision='APPROVED';r.approval={actor,at,digest:hash({...original(j),...r.draft})};r.dismissed=false;}
if(action==='schedule'){const t=new Date(body.scheduled_at);if(!Number.isFinite(+t)||+t<=Date.now())throw Error('FUTURE_SCHEDULE_REQUIRED');r.scheduled_at=t.toISOString();r.schedule_method='MANUAL_REMINDER';}
if(action==='reject'){r.decision='REJECTED';r.scheduled_at=null;}
if(action==='dismiss'){if(p.status!=='FAILED')throw Error('FAILED_POST_REQUIRED');r.dismissed=true;r.decision=null;r.scheduled_at=null;}
if(action==='manual'){if(r.decision!=='APPROVED'&&!( !r.history&&j.provider_state?.content_approval))throw Error('APPROVE_CONTENT_FIRST');if(body.confirm!==true||!url(body.public_url))throw Error('PUBLISHED_URL_AND_CONFIRMATION_REQUIRED');r.manual_published={at,actor,url:url(body.public_url)};r.scheduled_at=null;}
r.history=[...(r.history||[]),{action,actor,at}];if(['edit','regenerate'].includes(action))r.approval=null;
// Keep the transport state DRAFT and preparation_only: metadata approval can never enqueue an external post.
const provider={...j.provider_state,preparation_only:true,review_center:r};if(['edit','regenerate'].includes(action))provider.content_approval=null;
const state=['edit','regenerate'].includes(action)?'DRAFT':j.state;
await client.query('UPDATE social_queue_v1 SET provider_state=$2,state=$3,updated_at=now() WHERE id=$1',[id,provider,state]);await client.query('COMMIT');return {success:true,publishing_enabled:false};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function importLegacy(id,actor){const p=readPackages(roots).find(x=>x.id===id&&x.status!=='PUBLISHED'&&x.can_import);if(!p)throw Error('PACKAGE_NOT_FOUND');const client=await db.connect();try{await client.query('BEGIN');await client.query("INSERT INTO social_connections_v1(brand,platform) VALUES($1,$2) ON CONFLICT DO NOTHING",[p.brand,p.platform]);const idempotency='review_'+hash(id);await client.query("INSERT INTO social_queue_v1(id,brand,platform,account_id,generation,state,content,idempotency_key,provider_state) VALUES($1,$2,$3,'UNCONFIGURED',0,'DRAFT',$4,$5,$6) ON CONFLICT(brand,platform,idempotency_key) DO NOTHING",[crypto.randomUUID(),p.brand,p.platform,{legacy_id:id,campaign_id:p.campaign,product_name:p.product,topic:p.topic,text:p.caption,title:p.title,link:p.destination,image_url:p.creative,type:p.type},idempotency,{preparation_only:true,review_center:{history:[{action:'import',actor,at:new Date().toISOString()}]}}]);await client.query('COMMIT');return {success:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
return {snapshot,change,importLegacy,asset(brand,id,kind){return readPackages(roots).find(x=>x.brand===brand&&x.campaign===id&&x._asset?.kind===kind)?._asset?.file;}};
}
async function overview(db){const r=await db.query(`SELECT
(SELECT count(*)::int FROM users) customers,
(SELECT count(*)::int FROM subscriptions WHERE status='active') active_subscriptions,
(SELECT count(*)::int FROM subscriptions WHERE status IN ('past_due','unpaid')) payment_issues,
(SELECT count(*)::int FROM enterprise_requests WHERE status='pending') pending_enterprise,
(SELECT count(*)::int FROM withdrawals WHERE status='pending') pending_withdrawals,
(SELECT coalesce(sum(fee_amount),0) FROM fee_charges WHERE status IN ('paid','succeeded','completed')) collected_fees`);return {success:true,...r.rows[0]};}
function mount(router,{db,wrap,loadConfig}){router.get('/center/overview',wrap(async(req,res)=>res.json(await overview(db))));const center=createCenter({db,getConfig:loadConfig});router.get('/center',wrap(async(req,res)=>res.json(await center.snapshot())));router.post('/center/posts/:id',wrap(async(req,res)=>res.json(await center.change(req.params.id,req.body,String(req.user.id)))));router.post('/center/import',wrap(async(req,res)=>res.json(await center.importLegacy(req.body.id,String(req.user.id)))));router.get('/center/assets/:brand/:id/:kind',wrap(async(req,res)=>{const file=center.asset(req.params.brand,req.params.id,req.params.kind);if(!file)return res.status(404).end();res.set('X-Content-Type-Options','nosniff');res.sendFile(file);}));}
module.exports={overview,mount,createCenter,normalize,original,revision,readPackages};
