[build]
  command = "npm run build"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "frontend"
  command = "npm start"
