[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  functions = "netlify/functions"
  port = 8888
  publish = "public"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
