[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_API_URL = "https://api.imali-defi.com"
  REACT_APP_TG_NOTIFY_URL = "https://api.imali-defi.com/notify"

# SPA fallback (required for React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
