const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/route.js','utf8');
async function run({key='fixture',user={billing:{stripe_customer_id:'cus_fixture'}},data={data:[]},error}={}){let handler,reads=0,options;const logs=[];function Stripe(k,o){assert.equal(k,'fixture');options=o;this.subscriptions={list:async()=>{reads++;if(error)throw error;return data;}};}const sandbox={app:{get:(route,auth,fn)=>{assert.equal(route,'/api/billing/subscription');handler=fn;}},authenticateToken(){},Stripe,process:{env:{STRIPE_SECRET_KEY:key}},getUserById:async()=>user,parseJsonField:x=>x||{},authError:(res,status,message)=>{res.status=status;res.body={error:message};},console:{error:(...x)=>logs.push(x)}};vm.runInNewContext(source,sandbox);const res={status:200,json(body){this.body=body;return this;}};await handler({user:{id:'fixture'}},res);return {res,reads,options,logs};}
test('unpaid and missing subscription return explicit absence',async()=>{const r=await run();assert.equal(r.res.status,200);assert.equal(r.res.body.data.has_subscription,false);assert.equal(r.reads,1);});
test('paid subscription renders authoritative provider state',async()=>{const r=await run({data:{data:[{id:'sub_fixture',status:'active',items:{data:[{price:{nickname:'Pro',unit_amount:2500,currency:'usd',recurring:{interval:'month'}}}]}}]}});assert.equal(r.res.body.data.status,'active');assert.equal(r.res.body.data.plan,'Pro');assert.equal(r.options.timeout,15000);assert.equal(r.options.maxNetworkRetries,0);});
test('no billing customer skips provider request',async()=>{const r=await run({user:{billing:null}});assert.equal(r.reads,0);assert.equal(r.res.body.data.has_subscription,false);});
test('missing user rejected',async()=>assert.equal((await run({user:null})).res.status,404));
test('no configured provider renders unavailable',async()=>assert.equal((await run({key:''})).res.status,503));
test('null price/items remains renderable',async()=>{const r=await run({data:{data:[{status:'active',items:null}]}});assert.equal(r.res.status,200);assert.equal(r.res.body.data.plan,'Unknown');});
test('malformed provider data returns bounded failure state',async()=>assert.equal((await run({data:null})).res.status,503));
test('provider failure omits provider secrets and raw messages',async()=>{const r=await run({error:Object.assign(new Error('secret-provider-detail'),{type:'StripeAPIError',statusCode:500})});assert.equal(r.res.status,503);assert.equal(JSON.stringify(r).includes('secret-provider-detail'),false);});
