[build]
  command = "npm install && npm run build"
  publish = "build"

# WebSocket proxy
[[redirects]]
  from = "/socket.io/*"
  to = "http://129.213.90.84:8080/socket.io/:splat"
  status = 200
  force = true

# Catch all for React routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200