import FacebookPublisher from './FacebookPublisher';
import React, { useState, useEffect, useCallback } from 'react';
export default function SocialConnections({api}) {
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[test,setTest]=useState(null),[queue,setQueue]=useState([]);
 const [expected,setExpected]=useState({}),[text,setText]=useState(''),[link,setLink]=useState(''),[approved,setApproved]=useState(false),[type,setType]=useState('text'),[media,setMedia]=useState('');
 const reload=useCallback(async()=>{const [a,b]=await Promise.all([api.get('/api/admin/social/connections'),api.get('/api/admin/social/queue')]);setRows((a.connections?a:a.data).connections);setQueue((b.items?b:b.data).items);},[api]);
 useEffect(()=>{reload().catch(()=>setError('Unable to load connections.'));},[reload]);
 async function act(fn){setBusy(true);setError('');try{await fn();await reload();}catch(e){setError(e.response?.data?.error||e.message||'Action could not be completed.');}finally{setBusy(false);}}
 const base=r=>`/api/admin/social/${r.brand}/${r.platform}`;
 function connect(r){act(async()=>{const res=await api.post(base(r)+'/connect',{expected_account_id:r.account_id||expected[r.brand+':'+r.platform]},{withCredentials:true});window.location.assign(res.authorization_url||res.data.authorization_url);});}
 function submit(){const r=test;act(async()=>{const body={brand:r.brand,account_id:r.account_id,idempotency_key:r.testKey,approve:approved,type,text,link:link||null,caption:text,media_url:media};const res=await api.post(base(r)+(r.platform==='instagram'?'/media-tests':'/test-post'),body);const data=res.data?.data||res.data;if(r.platform!=='instagram'&&data?.state!=='POSTED')throw Error(data?.error||'Posting not confirmed. Check results before retrying.');setTest(null);});}
 const button='rounded-lg bg-indigo-600 px-3 py-2 m-1 disabled:opacity-40 hover:bg-indigo-500';
 const input='block w-full rounded-lg bg-gray-800 border border-gray-600 p-3 my-2 text-white';
 return <section aria-label="Social Connections" className="space-y-6"><h1 className="text-3xl font-bold">Social Connections</h1><p>Manual connection and test mode. Unattended publishing is disabled.</p>{error&&<p role="alert" className="text-amber-300">{error}</p>}
 <FacebookPublisher api={api} connections={rows} onChanged={reload}/>
 {['imali','sports_jedi'].map(brand=><section key={brand} className="rounded-xl bg-gray-900 p-4"><h2 className="text-xl font-semibold mb-4">{brand==='imali'?'IMALI':'Sports Jedi'}</h2><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Platform</th><th>Destination</th><th>Status</th><th>Controls</th></tr></thead><tbody>{rows.filter(r=>r.brand===brand).map(r=><tr key={r.platform} className="border-t border-gray-700"><td className="p-2">{r.platform.toUpperCase()}</td><td className="p-2">{r.account_name||'No verified account'} {r.account_id&&<small className="block">{r.account_id}</small>}{!r.account_id&&<input className={input} aria-label={`${brand} ${r.platform} expected account ID`} placeholder="Expected account ID" value={expected[brand+':'+r.platform]||''} onChange={e=>setExpected({...expected,[brand+':'+r.platform]:e.target.value})}/>}</td><td className="p-2">{r.connection_status}{!r.app_configured&&' — app setup required'}<br/>{r.last_error||''}</td><td className="p-2"><button className={button} disabled={busy||!r.app_configured} onClick={()=>connect(r)}>{r.account_id?'Reconnect':'Connect'}</button>{r.connection_status==='PENDING_CONFIRMATION'&&<button className={button} disabled={busy} onClick={()=>act(()=>api.post(base(r)+'/confirm',{account_id:r.account_id}))}>Confirm {brand} destination</button>}<button className={button} disabled={busy||r.connection_status==='DISCONNECTED'} onClick={()=>act(()=>api.post(base(r)+'/disconnect'))}>Disconnect</button><button className={button} disabled={busy||r.connection_status!=='CONNECTED'||!r.test_types.length} onClick={()=>{setTest({...r,testKey:crypto.randomUUID()});setText('');setLink('');setMedia('');setType(r.test_types[0]);setApproved(false);}}>Test Post</button></td></tr>)}</tbody></table></div></section>)}
 {test&&<section aria-label="Test post preview" className="rounded-xl bg-gray-900 p-6"><h2 className="text-xl font-semibold">Test post to {test.brand} / {test.platform}</h2><p>Destination: {test.account_name} ({test.account_id}). This test will be visible according to platform settings.</p><label>Post type<select className={input} value={type} onChange={e=>{setType(e.target.value);setApproved(false);}}>{test.test_types.map(t=><option key={t}>{t}</option>)}</select></label><label>Exact text / caption<textarea className={input} value={text} onChange={e=>{setText(e.target.value);setApproved(false);}}/></label>{test.platform==='instagram'?<label>Approved public media URL<input className={input} type="url" value={media} onChange={e=>{setMedia(e.target.value);setApproved(false);}}/><small>Use an approved media origin for this brand. Image or Reel required; no standalone text posts.</small></label>:type==='link'&&<label>HTTPS link<input className={input} value={link} onChange={e=>{setLink(e.target.value);setApproved(false);}}/></label>}<label className="block my-4"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I approve this exact test content and destination.</label><button className={button} disabled={busy||!approved||(test.platform==='instagram'?!media:!text.trim())} onClick={submit}>{test.platform==='instagram'?'Approve media test':'Publish this test'}</button><button className={button} onClick={()=>setTest(null)}>Cancel</button></section>}
 <section><h2 className="text-xl font-semibold">Test results</h2><p className="text-white/70">Instagram: advance one step at a time. Wait at least one minute between processing checks. READY means ready to publish, not posted. Uncertain outcomes require review and must not be retried.</p><button className={button} disabled={busy} onClick={()=>act(async()=>{})}>Refresh results</button>{queue.map(j=><div key={j.id} className="border-b border-gray-700 py-3"><strong>{j.brand} / {j.platform}</strong> — {j.platform==='facebook'?(j.provider_state?.status||j.state):j.state} {j.provider_state?.step}<p>{j.error}</p>{j.platform_post_id&&<p>Platform ID: {j.platform_post_id}</p>}{j.platform==='facebook'&&j.state==='RETRY'&&<button className={button} disabled={busy||(j.provider_state?.retry_at&&Date.parse(j.provider_state.retry_at)>Date.now())} onClick={()=>act(()=>api.post(`/api/admin/social/imali/facebook/posts/${j.id}/retry`,{approve:true}))}>Retry Facebook when due</button>}{j.public_url&&<a className="text-emerald-400 underline" href={j.public_url} target="_blank" rel="noreferrer">View confirmed post</a>}{j.platform==='instagram'&&!['POSTED','FAILED'].includes(j.state)&&['NEW','PROCESSING','READY','CONFIRMING'].includes(j.provider_state?.step)&&<button className={button} disabled={busy} onClick={()=>act(()=>api.post(`/api/admin/social/${j.brand}/instagram/media-tests/${j.id}/advance`,{brand:j.brand,account_id:j.account_id,approve:true}))}>{j.provider_state.step==='READY'?'Publish approved Instagram test':'Advance approved test'}</button>}</div>)}</section>
 </section>;
}
