// src/components/enterprise/audit/AuditLogExport.js
import React from 'react';

const AuditLogExport = ({ logs, onExport }) => {
  const handleExportCSV = () => {
    if (!logs || logs.length === 0) {
      alert('No logs to export');
      return;
    }

    // Define CSV headers
    const headers = [
      'Timestamp',
      'User Email',
      'Action',
      'Details',
      'IP Address',
      'User Agent'
    ];

    // Format rows
    const rows = logs.map(log => [
      new Date(log.created_at).toLocaleString(),
      log.user_email || log.user_id || 'System',
      log.action,
      JSON.stringify(log.details || {}),
      log.ip_address || 'N/A',
      log.user_agent || 'N/A'
    ]);

    // Create CSV content
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    ].join('\n');

    // Download file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const timestamp = new Date().toISOString().split('T')[0];
    
    link.href = url;
    link.setAttribute('download', `audit-logs-${timestamp}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    if (onExport) onExport();
  };

  const handleExportJSON = () => {
    if (!logs || logs.length === 0) {
      alert('No logs to export');
      return;
    }

    const data = {
      exported_at: new Date().toISOString(),
      count: logs.length,
      logs: logs
    };

    const jsonContent = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const timestamp = new Date().toISOString().split('T')[0];
    
    link.href = url;
    link.setAttribute('download', `audit-logs-${timestamp}.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    if (onExport) onExport();
  };

  const handleExportPDF = async () => {
    if (!logs || logs.length === 0) {
      alert('No logs to export');
      return;
    }

    // Create a hidden iframe for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to export PDF');
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Audit Logs Export</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 20px;
          }
          h1 {
            color: #333;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 10px;
          }
          .info {
            color: #666;
            margin-bottom: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background-color: #4f46e5;
            color: white;
            padding: 10px;
            text-align: left;
          }
          td {
            border: 1px solid #ddd;
            padding: 8px;
            vertical-align: top;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          .footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <h1>IMALI Enterprise Audit Logs</h1>
        <div class="info">
          <p>Exported: ${new Date().toLocaleString()}</p>
          <p>Total Records: ${logs.length}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>User</th>
              <th>Action</th>
              <th>Details</th>
            </tr>
          </thead>
          <tbody>
            ${logs.map(log => `
              <tr>
                <td>${new Date(log.created_at).toLocaleString()}</td>
                <td>${log.user_email || log.user_id || 'System'}</td>
                <td>${log.action}</td>
                <td>${JSON.stringify(log.details || {}).substring(0, 100)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">
          <p>Generated by IMALI Enterprise Platform</p>
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="relative inline-block">
      <div className="flex gap-2">
        <button
          onClick={handleExportCSV}
          className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Export CSV
        </button>
        
        <button
          onClick={handleExportJSON}
          className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          Export JSON
        </button>
        
        <button
          onClick={handleExportPDF}
          className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          Print / PDF
        </button>
      </div>
    </div>
  );
};

export default AuditLogExport;