const fs=require('fs'),cp=require('child_process'),assert=require('assert/strict'),crypto=require('crypto');const app='/home/opc/imali-sniper',stage='/tmp/imali-admin-center-20260920';
const pid=cp.execFileSync('systemctl',['show','user-api.service','--property=MainPID','--value'],{encoding:'utf8'}).trim();const env=Object.fromEntries(fs.readFileSync('/proc/'+pid+'/environ','utf8').split('\0').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1)];}));process.env.CREDENTIALS_DIRECTORY=env.CREDENTIALS_DIRECTORY;
const dbEnv=require(app+'/node_modules/dotenv').parse(fs.readFileSync('/etc/imali-marketing.env'));const {Pool}=require(app+'/node_modules/pg');const db=new Pool({connectionString:dbEnv.DATABASE_URL});
(async()=>{try{for(let i=0;i<20;i++){try{const r=await fetch('http://127.0.0.1:3000/health');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}const user=(await db.query("SELECT id,email,is_admin FROM users WHERE email='wayne@imali-defi.com'")).rows[0];assert(user);const jwt=require(app+'/node_modules/jsonwebtoken');const token=jwt.sign({id:user.id,email:user.email},require(app+'/node_modules/dotenv').parse(fs.readFileSync(app+'/.env')).JWT_SECRET,{expiresIn:'2m'});const get=async(path,auth=true)=>{const r=await fetch('http://127.0.0.1:3000'+path,{headers:auth?{Authorization:'Bearer '+token}:{}});return {status:r.status,body:await r.json()};};
const unauth=await get('/api/admin/social/center',false);assert.equal(unauth.status,401);
for(const [endpoint,file] of [['/api/admin/social/center','api-social.json'],['/api/admin/social/center/overview','api-business.json'],['/api/admin/work-agent/engine/summary','api-engine-summary.json'],['/api/admin/work-agent/engine/health','api-engine-health.json'],['/api/health','api-health.json']]){const r=await get(endpoint);assert.equal(r.status,200);fs.writeFileSync(stage+'/'+file,JSON.stringify(r.body));}
const social=JSON.parse(fs.readFileSync(stage+'/api-social.json'));const creative=social.library.find(p=>p.creative&&p.platform==='linkedin');if(creative){const r=await fetch('http://127.0.0.1:3000'+creative.creative,{headers:{Authorization:'Bearer '+token}});assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/image/);fs.writeFileSync(stage+'/preview-image.png',Buffer.from(await r.arrayBuffer()));fs.writeFileSync(stage+'/preview-image.json',JSON.stringify({path:creative.creative,id:creative.id}));}
const F=require(app+'/social/facebook-service').loadConfig();assert.equal(F.enabled,false);const config=JSON.parse(fs.readFileSync('/etc/imali-social/config.json'));assert.equal(config.automatic_publishing,false);assert.equal(config.manual_test_enabled,false);
const sql=(await db.query('SELECT state,count(*)::int n FROM social_queue_v1 GROUP BY state')).rows;
const engine=JSON.parse(fs.readFileSync(stage+'/api-engine-summary.json'));assert.equal(['AUTO_PROCESSING','ACTION_REQUIRED','BLOCKED_EXTERNAL','DISPOSED','COMPLETED'].reduce((a,k)=>a+engine.counts[k],0),engine.counts.total);
const protectedBackup=fs.readdirSync('/var/backups').filter(x=>x.startsWith('imali-admin-center-')).sort().pop();const protectedFiles=JSON.parse(fs.readFileSync('/var/backups/'+protectedBackup+'/protected.json'));for(const [file,digest] of Object.entries(protectedFiles))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),digest,file);
console.log(JSON.stringify({success:true,counts:social.counts,queue:sql,library:social.library.length,protected_files_unchanged:Object.keys(protectedFiles).length,facebook_publishing:false,automatic_publishing:false,manual_tests:false,unauthenticated_request:unauth.status,asset_preview:!!creative,external_publish_requests:0,opportunity_total:engine.counts.total,platforms:social.platforms.map(p=>({brand:p.brand,platform:p.platform,status:p.connection_status,capability:p.capability}))}));
}finally{await db.end();}})().catch(e=>{console.error(e.message);process.exitCode=1});
