// src/constants/auditActions.js
export const AUDIT_ACTIONS = {
  INVITE_USER: 'INVITE_USER',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  CREATE_CUSTOM_STRATEGY: 'CREATE_CUSTOM_STRATEGY',
  UPDATE_CUSTOM_STRATEGY: 'UPDATE_CUSTOM_STRATEGY',
  DELETE_CUSTOM_STRATEGY: 'DELETE_CUSTOM_STRATEGY',
  UPDATE_BRANDING: 'UPDATE_BRANDING',
  UPDATE_BOT_CONTROLS: 'UPDATE_BOT_CONTROLS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
};

export const AUDIT_ACTION_LABELS = {
  [AUDIT_ACTIONS.INVITE_USER]: 'User Invited',
  [AUDIT_ACTIONS.REMOVE_USER]: 'User Removed',
  [AUDIT_ACTIONS.UPDATE_USER_ROLE]: 'User Role Updated',
  [AUDIT_ACTIONS.CREATE_CUSTOM_STRATEGY]: 'Custom Strategy Created',
  [AUDIT_ACTIONS.UPDATE_CUSTOM_STRATEGY]: 'Custom Strategy Updated',
  [AUDIT_ACTIONS.DELETE_CUSTOM_STRATEGY]: 'Custom Strategy Deleted',
  [AUDIT_ACTIONS.UPDATE_BRANDING]: 'Branding Updated',
  [AUDIT_ACTIONS.UPDATE_BOT_CONTROLS]: 'Bot Controls Updated',
  [AUDIT_ACTIONS.CREATE_ORGANIZATION]: 'Organization Created',
  [AUDIT_ACTIONS.UPDATE_ORGANIZATION]: 'Organization Updated',
};

export const AUDIT_ACTION_ICONS = {
  [AUDIT_ACTIONS.INVITE_USER]: '👤',
  [AUDIT_ACTIONS.REMOVE_USER]: '❌',
  [AUDIT_ACTIONS.UPDATE_USER_ROLE]: '🔄',
  [AUDIT_ACTIONS.CREATE_CUSTOM_STRATEGY]: '📊',
  [AUDIT_ACTIONS.UPDATE_CUSTOM_STRATEGY]: '✏️',
  [AUDIT_ACTIONS.DELETE_CUSTOM_STRATEGY]: '🗑️',
  [AUDIT_ACTIONS.UPDATE_BRANDING]: '🎨',
  [AUDIT_ACTIONS.UPDATE_BOT_CONTROLS]: '🤖',
};