'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const D=require('../social/destinations'),M=require('../social/threads-media'),A=require('../social/automation');
test('fixed product and founder identities cannot be cross-authorized',()=>{D.assertUsername('imali','threads','@imali_defi');D.assertUsername('founder','instagram','whoisblackgriff');assert.throws(()=>D.assertUsername('imali','threads','whoisblackgriff'),/DESTINATION_MISMATCH/);assert.throws(()=>D.assertUsername('sports_jedi','threads','imali_defi'),/DESTINATION_MISMATCH/)});
test('public media validation rejects private, credentialed, wrong-brand and overlength content',()=>{for(const media_url of ['http://api.imali-defi.com/api/blog/images/x.png','https://127.0.0.1/x.png','https://api.sportsjedi.com/api/blog/images/x.png','https://user:pass@api.imali-defi.com/api/blog/images/x.png'])assert.throws(()=>M.validate('imali',{caption:'x',media_url}));assert.throws(()=>M.validate('imali',{caption:'x'.repeat(501),media_url:'https://api.imali-defi.com/api/blog/images/x.png'}));assert.equal(M.validate('imali',{caption:'x',media_url:'https://api.imali-defi.com/api/blog/images/x.png'}).type,'image')});
function worker(job,{failConfirm=false}={}){
 let publishes=0,creates=0;const c={brand:'imali',account_id:'123',account_name:'imali_defi',generation:1,connection_status:'CONNECTED',token_cipher:'encrypted'};
 const client={release(){},async query(sql,args=[]){if(sql.includes('pg_try'))return {rows:[{ok:true}]};if(sql.includes('SELECT * FROM social_queue'))return {rows:[job]};if(sql.includes('SELECT * FROM social_connections'))return {rows:[c]};if(sql.includes('UPDATE social_queue')){if(sql.includes("state='POSTED'")){job.state='POSTED';job.provider_state=args[1];job.platform_post_id=args[2];}else{job.state=args[1];job.provider_state=args[2];job.error=args[3];}}return {rows:[]}}};
 const modules={'node:fs':{readFileSync(file){return file.endsWith('vault.key')?Buffer.alloc(32).toString('base64'):JSON.stringify({apps:{threads:{client_id:'test',client_secret:'test'}}})}},'./campaign-db':{},'./campaign-runtime':{postgres:()=>({Pool:function(){}}),social:name=>name==='security'?{open:()=>({access_token:'test'})}:name==='campaign-guard'?{assertNotPreparedCampaign(){}}:{checkMedia:async()=>({}),create:async()=>{creates++;return '456'},status:async()=>'FINISHED',publish:async()=>{publishes++;return '789'},confirm:async()=>{if(failConfirm)throw Error('PERMALINK_UNAVAILABLE');return {id:'789',url:'https://www.threads.com/@imali_defi/post/abc'}}}}};
 const sandbox={module:{exports:{}},require:n=>modules[n],Buffer,Date,console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../marketing/threads-worker.js'),'utf8'),sandbox);return {advance:()=>sandbox.module.exports.advance({connect:async()=>client},job.id),counts:()=>({publishes,creates})};
}
const job=step=>({id:'j',brand:'imali',platform:'threads',account_id:'123',generation:1,state:'APPROVED',approved_by:'admin',provider_state:{step},content:{}});
test('crashed in-flight job enters review without recreating or publishing',async()=>{const j=job('PUBLISHING'),w=worker(j);const r=await w.advance();assert.equal(r.state,'REVIEW');assert.equal(w.counts().publishes,0);assert.equal(j.error,'CONFIRMATION_UNKNOWN_DO_NOT_RETRY')});
test('durable container is reused and confirmed publication is never replayed',async()=>{const j=job('NEW'),w=worker(j);await w.advance();assert.equal(j.provider_state.container_id,'456');await w.advance();await w.advance();assert.equal(j.state,'POSTED');assert.equal(w.counts().creates,1);assert.equal(w.counts().publishes,1)});
test('confirmation failure retains media ID and requires review without retry',async()=>{const j=job('NEW'),w=worker(j,{failConfirm:true});await w.advance();await w.advance();await w.advance();assert.equal(j.provider_state.media_id,'789');assert.equal(j.provider_state.step,'REVIEW');assert.equal(w.counts().publishes,1)});
test('automation settings validate supported destination and time formats',()=>{assert.equal(A.validateSetting({brand:'imali',platform:'threads',content_type:'stock',posting_windows:['08:30']}).timezone,'America/New_York');assert.throws(()=>A.validateSetting({brand:'founder',platform:'threads',content_type:'stock'}));assert.throws(()=>A.validateSetting({brand:'imali',platform:'threads',content_type:'stock',posting_windows:['25:00']}))});

test('draft content remains editable even when its preparer is recorded',()=>{const p=require('../social/center').normalize({id:'draft',brand:'imali',platform:'tiktok',state:'DRAFT',approved_by:'preparer',provider_state:{},content:{caption:'Draft'}});assert.equal(p.editable,true)});
