const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const source=fs.readFileSync(__dirname+'/route.js','utf8');
async function run(options={}){const calls=[],sql=[],logs=[];let handler;const base={id:'sub_fixture',customer:'cus_fixture',status:'active',cancel_at_period_end:false,metadata:{user_id:'u1'},items:{data:[{price:{id:'price_pro'}}]}};const sub={...base,...options.sub};const user=options.user===undefined?{id:'u1',stripe_customer_id:'cus_fixture',stripe_subscription_id:'sub_fixture',billing:{}}:options.user;function Stripe(){return {subscriptions:{retrieve:async()=>{calls.push('retrieve');return sub},list:async()=>{calls.push('list');return {data:options.list||[sub],has_more:!!options.hasMore}},update:async()=>{calls.push('update');if(options.providerFail)throw Error('secret-provider-detail');return {...sub,cancel_at_period_end:true,...options.confirmation}}}};}const sandbox={app:{post:(url,auth,fn)=>handler=fn},authenticateToken(){},Stripe,process:{env:{STRIPE_SECRET_KEY:options.unconfigured?'':'fixture',STRIPE_PRICE_PRO:'price_pro',STRIPE_PRICE_ELITE:'price_elite'}},getUserById:async()=>user,parseJsonField:x=>x||{},db:{query:async text=>{calls.push('database');sql.push(text);if(options.dbFail)throw Error('private-db-detail');}},addAuditLog:async()=>calls.push('audit'),console:{error:(...x)=>logs.push(x)},authError:(res,n,error)=>res.status(n).json({success:false,error})};vm.runInNewContext(source,sandbox);const res={statusCode:200,status(n){this.statusCode=n;return this},json(body){this.body=body;return this}};await handler({user:{id:'u1'}},res);return {res,calls,sql,logs};}
test('provider confirms cancellation before local writes; entitlement flags untouched',async()=>{const r=await run();assert.equal(r.res.statusCode,200);assert.deepEqual(r.calls,['retrieve','update','database','audit']);assert.equal(r.res.body.data.subscription_status,'active');assert.equal(r.sql.some(s=>/trading_enabled|paper_trading_enabled|subscription_status|SET tier/i.test(s)),false);});
test('unconfigured client fails before any provider/database write',async()=>{const r=await run({unconfigured:true});assert.equal(r.res.statusCode,503);assert.deepEqual(r.calls,[]);});
test('missing account rejected',async()=>assert.equal((await run({user:null})).res.statusCode,404));
test('provider failure leaves local account unchanged',async()=>{const r=await run({providerFail:true});assert.equal(r.res.statusCode,503);assert.equal(r.calls.includes('database'),false);assert.equal(JSON.stringify(r).includes('secret-provider-detail'),false);});
test('different customer cannot be cancelled',async()=>{const r=await run({sub:{customer:'cus_other'}});assert.equal(r.res.statusCode,409);assert.equal(r.calls.includes('update'),false);});
test('different metadata owner cannot be cancelled',async()=>{const r=await run({sub:{metadata:{user_id:'other'}}});assert.equal(r.res.statusCode,409);assert.equal(r.calls.includes('update'),false);});
test('addon subscription cannot be mistaken for base plan',async()=>{const r=await run({sub:{items:{data:[{price:{id:'price_addon'}}]}}});assert.equal(r.res.statusCode,409);assert.equal(r.calls.includes('update'),false);});
test('unlinked customer needs explicit support review',async()=>{const r=await run({user:{id:'u1',billing:{}}});assert.equal(r.res.statusCode,409);assert.deepEqual(r.calls,[]);});
test('legacy missing subscription ID resolves one owned base subscription',async()=>{const r=await run({user:{id:'u1',stripe_customer_id:'cus_fixture',billing:{}}});assert.equal(r.res.statusCode,200);assert.deepEqual(r.calls,['list','update','database','audit']);});
test('ambiguous list and pagination block cancellation',async()=>{for(const extra of [{list:[{id:'a',status:'active',items:{data:[{price:{id:'price_pro'}}]}},{id:'b',status:'active',items:{data:[{price:{id:'price_pro'}}]}}]},{hasMore:true}]){const r=await run({user:{id:'u1',stripe_customer_id:'cus_fixture',billing:{}},...extra});assert.equal(r.res.statusCode,409);assert.equal(r.calls.includes('update'),false);}});
test('already-ended subscription has no mutation',async()=>{const r=await run({sub:{status:'canceled'}});assert.equal(r.res.statusCode,200);assert.equal(r.res.body.cancellation_scheduled,false);assert.deepEqual(r.calls,['retrieve']);});
test('repeat scheduled cancellation does not repeat provider mutation',async()=>{const r=await run({sub:{cancel_at_period_end:true}});assert.equal(r.res.statusCode,200);assert.deepEqual(r.calls,['retrieve','database','audit']);});
test('incomplete state is not silently converted to period-end cancellation',async()=>{const r=await run({sub:{status:'incomplete'}});assert.equal(r.res.statusCode,409);assert.equal(r.calls.includes('update'),false);});
test('confirmed provider outcome remains truthful if local bookkeeping fails',async()=>{const r=await run({dbFail:true});assert.equal(r.res.statusCode,200);assert.equal(r.res.body.cancellation_scheduled,true);assert.equal(JSON.stringify(r).includes('private-db-detail'),false);});
test('unconfirmed or wrong-ID provider response cannot claim success',async()=>{for(const confirmation of [{cancel_at_period_end:false},{id:'sub_other'}]){const r=await run({confirmation});assert.equal(r.res.statusCode,503);assert.equal(r.calls.includes('database'),false);}});
