import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../hooks/useAuth";   // axios wrapper
import TierLock from "./TierLock";   // optional helper

export default function Futures() {
  const { user, tier } = useAuth();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [signal, setSignal] = useState(null);
  const [error, setError] = useState("");

  const isElite = tier === "elite" || tier === "bundle";

  useEffect(() => {
    if (!isElite) {
      setLoading(false);
      return;
    }

    loadSignal();
  }, [tier]);

  async function loadSignal() {
    try {
      setLoading(true);
      const res = await api.get("/api/telegram/futures-signal");
      setSignal(res.data);
    } catch (err) {
      setError("Failed to load futures signal");
    } finally {
      setLoading(false);
    }
  }

  /* ------------------ RENDER ------------------ */

  if (!isElite) {
    return (
      <div className="max-w-3xl mx-auto py-10">
        <div className="rounded-xl border border-white/10 bg-black/40 p-6">
          <h1 className="text-2xl font-bold mb-3">
            ⚡ Futures Signals
          </h1>

          <p className="text-slate-300 mb-6">
            Futures signals are reserved for <strong>Elite</strong> members.
            These are high-conviction, leverage-aware trades generated by the IMALI engine.
          </p>

          {/* Demo Card */}
          <div className="rounded-lg bg-white/5 border border-white/10 p-4 mb-6">
            <div className="text-sm text-slate-400 mb-2">Demo Signal</div>
            <div className="font-mono text-slate-200">
              BTC-USDT · LONG<br />
              Entry: 41,200<br />
              TP: 42,600<br />
              SL: 40,750
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="text-sm text-slate-400">
              🔒 You’re 1 upgrade away from Elite
            </div>

            <button
              onClick={() => navigate("/pricing")}
              className="px-4 py-2 rounded-lg bg-indigo-500 hover:bg-indigo-600 text-white font-medium"
            >
              Upgrade to Elite
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-10">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">
          ⚡ Live Futures Signal
        </h1>

        <button
          onClick={loadSignal}
          className="text-sm px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20"
        >
          Refresh
        </button>
      </div>

      {loading && (
        <div className="rounded-lg bg-white/5 p-6 text-slate-400">
          Loading signal…
        </div>
      )}

      {error && (
        <div className="rounded-lg bg-red-500/10 border border-red-500/20 p-4 text-red-400">
          {error}
        </div>
      )}

      {signal && (
        <div className="rounded-xl border border-white/10 bg-black/40 p-6">
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <div className="text-xs text-slate-400">Symbol</div>
              <div className="font-semibold">{signal.symbol}</div>
            </div>

            <div>
              <div className="text-xs text-slate-400">Direction</div>
              <div
                className={`font-semibold ${
                  signal.direction === "LONG"
                    ? "text-green-400"
                    : "text-red-400"
                }`}
              >
                {signal.direction}
              </div>
            </div>

            <div>
              <div className="text-xs text-slate-400">Entry</div>
              <div>{signal.entry}</div>
            </div>

            <div>
              <div className="text-xs text-slate-400">Stop Loss</div>
              <div>{signal.stop_loss}</div>
            </div>

            <div>
              <div className="text-xs text-slate-400">Take Profit</div>
              <div>{signal.take_profit}</div>
            </div>

            <div>
              <div className="text-xs text-slate-400">Confidence</div>
              <div>{signal.confidence}%</div>
            </div>
          </div>

          <div className="text-xs text-slate-400">
            Generated {new Date(signal.timestamp).toLocaleString()}
          </div>
        </div>
      )}

      <div className="mt-6 text-xs text-slate-500">
        🔔 Tip: Enable Telegram alerts to receive futures signals instantly.
      </div>
    </div>
  );
}
