import React,{useState,useEffect,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {apiFetch} from '../context/AuthContext';
import '../pages/admin/SocialMediaCenter.css';
export function useAdminAttention(){const [data,setData]=useState({items:[],errors:[],loading:true});const refresh=useCallback(async()=>{const endpoints=['/api/admin/social/center','/api/admin/work-agent/engine/summary','/api/admin/social/center/overview','/api/admin/work-agent/engine/health','/api/health'];const r=await Promise.allSettled(endpoints.map(p=>apiFetch(p)));const values=r.map(x=>x.status==='fulfilled'?x.value:null);const [social,opportunity,business,health,api]=values;const items=[];const add=(count,label,to)=>{if(Number(count)>0)items.push({count:Number(count),label,to});};add(social?.counts?.NEEDS_APPROVAL,'Social Posts Need Approval','/admin/social');add(social?.counts?.FAILED,'Social Publishing Failures','/admin/social?status=FAILED');add(opportunity?.counts?.ACTION_REQUIRED,'Opportunity Decisions','/admin/work-agent');add(business?.pending_enterprise,'Enterprise Requests','/admin?tab=enterprise-requests');add(business?.pending_withdrawals,'Withdrawal Reviews','/admin?tab=withdrawals');add(business?.payment_issues,'Customer Payment Issues','/admin/billing');const broken=(health?.services||[]).filter(x=>x.ActiveState==='failed');add(broken.length,'Failed Services','/admin?tab=health');setData({social,opportunity,business,health,api,items,total:items.reduce((a,x)=>a+x.count,0),errors:r.map((x,i)=>x.status==='rejected'?['Social publishing','Opportunity summary','Business summary','Service health','Database/API'][i]:null).filter(Boolean),loading:false});},[]);useEffect(()=>{refresh();const t=setInterval(refresh,60000);window.addEventListener('imali-attention-refresh',refresh);return()=>{clearInterval(t);window.removeEventListener('imali-attention-refresh',refresh);};},[refresh]);return {...data,refresh};}
export function AttentionBadge(){const d=useAdminAttention();return <Link className="rounded-xl border border-amber-400/30 bg-amber-400/10 px-3 py-2 text-xs text-amber-100" to="/admin?tab=attention">Needs your attention <strong>{d.loading?'…':d.total}{d.errors.length?' + ?':''}</strong></Link>;}
function Attention({d}){return <section className="sm-attention"><h2>Needs your attention</h2>{d.errors.length>0&&<p className="sm-error">Some counts are unavailable: {d.errors.join(', ')}. The attention total is partial. <button onClick={d.refresh}>Retry</button></p>}<div className="sm-posts">{d.items.map(i=><Link className="sm-post" key={i.label} to={i.to}><strong style={{fontSize:25}}>{i.count}</strong><b>{i.label} →</b></Link>)}</div>{!d.loading&&!d.items.length&&!d.errors.length&&<p>No human actions are currently queued.</p>}</section>;}
export default function AdminExecutiveOverview({attentionOnly=false}){const d=useAdminAttention(),b=d.business,c=d.opportunity?.counts;const value=x=>x===null||x===undefined?'Unavailable':Number(x).toLocaleString();return <div className="sm-center sm-executive" style={{minHeight:0,padding:0}}><Attention d={d}/>{!attentionOnly&&<><h2 style={{margin:'28px 0 14px'}}>Business snapshot</h2><div className="sm-posts">{[[b?.collected_fees,'Collected trading fees (USD)','/admin?tab=fees'],[b?.customers,'Customers','/admin?tab=users'],[b?.active_subscriptions,'Active subscriptions','/admin/billing'],[c?.actual_revenue_amount,'Opportunity actual revenue (USD)','/admin/work-agent'],[c?.won,'Opportunities won','/admin/work-agent'],[d.social?.counts?.PUBLISHED,'Recorded social publications','/admin/social?status=PUBLISHED']].map(([n,label,href])=><Link className="sm-post" key={label} to={href}><strong style={{fontSize:25}}>{value(n)}</strong><span>{label} →</span></Link>)}</div><p className="sm-muted">Collected fees are from the existing fee ledger. Subscription revenue is not available in that ledger; trading P&amp;L is not business revenue.</p><h2 style={{margin:'28px 0 14px'}}>System status</h2><div className="sm-posts"><Link className="sm-post" to="/admin?tab=health"><b>Trading</b><span>{d.health?.services?.filter(s=>/trading|executor|bot/.test(s.unit)).map(s=>`${s.unit}: ${s.ActiveState}`).join(' · ')||'Open System Health for service status'} →</span></Link><Link className="sm-post" to="/admin/work-agent"><b>Opportunity Autopilot</b><span>{d.health?.timers?.map(t=>`${t.unit}: ${t.ActiveState}`).join(' · ')||'Status unavailable'} →</span></Link><Link className="sm-post" to="/admin/social"><b>Social publishing</b><span>{d.social?'Shared queue: manual posting; automatic publishing disabled':'Status unavailable'} →</span></Link><Link className="sm-post" to="/admin?tab=health"><b>Database / API</b><span>{d.api?.success&&d.api?.status==='ok'?'Healthy':d.api?.status||'Status unavailable'} →</span></Link></div></>}</div>;}
export function AdminAttention(){return <AdminExecutiveOverview attentionOnly/>;}
