import React, {useState,useEffect,useCallback} from 'react';
import BotAPI from '../../utils/BotAPI';
import './AdminWorkAgent.css';
const endpoint='/api/admin/work-agent/engine';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
const number=v=>Number(v||0).toLocaleString();
const label=s=>String(s||'Unknown').replace(/_/g,' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase());
const when=v=>v?new Date(v).toLocaleString():'Not recorded';
const lanes=['ALL','Commercial','Government','Subcontractor','Rewards','Recovery','Employment'];
const stages=['Discovered','Researching','Qualified','Needs Documents','Needs Registration/Auth','Package Building','Package Ready','Needs Provider','Final Bid Approval','Submitted','Won','Lost','Disposed'];
const providerStages=['Delivery Analysis','Needs Provider','Searching','Candidates Found','Needs Provider Approval','Provider Approved','Package Ready','Final Approval'];
const get=async(path,params)=> (await BotAPI.api.get(endpoint+path,{params})).data;
function Source({url,children='View source'}){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?<a href={url} target="_blank" rel="noreferrer">{children}</a>:null;}catch{return null;}}
export default function AdminWorkAgent(){
 const [summary,setSummary]=useState(null),[filter,setFilter]=useState({metric:'ACTION_REQUIRED',exclude_employment:'1'}),[records,setRecords]=useState({items:[],total:0}),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[detail,setDetail]=useState(null),[recovery,setRecovery]=useState(null),[health,setHealth]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[subject,setSubject]=useState(''),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{try{setSummary(await get('/summary'));setHealth(await get('/health'));}catch(e){setError(e.response?.data?.error||e.message);}},[]);
 useEffect(()=>{refresh();const t=setInterval(refresh,60000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{let alive=true;setBusy(true);get('/records',{...filter,search,offset,limit:10}).then(r=>{if(alive){setRecords(r);setError('');}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false;};},[filter,search,offset,summary]);
 function select(f){setFilter(f);setOffset(0);setRecovery(null);document.getElementById('engine-records')?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function open(id){try{const d=await get('/records/'+id);setDetail(d);setSubject(d.item.outreach_subject||'');setMessage(d.item.outreach_body||'');setNote('');}catch(e){setError(e.message);}}
 async function decision(action,extra={}){setBusy(true);try{const r=(await BotAPI.api.post(endpoint+'/records/'+detail.item.id+'/decision',{action,note,subject,message,...extra})).data;setNotice(r.message);await open(detail.item.id);await refresh();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
 async function jurisdictions(state){try{setRecovery((await get('/recovery',{state})).items);}catch(e){setError(e.message);}}
 const c=summary?.counts||{},groups=summary?.groups||{};
 const count=(group,key)=>(groups[group]||[]).find(x=>x.label===key)?.count||0;
 const selectedLane=filter.lane||'ALL';
 return <main className="oe">
  <header className="oe-head"><div><small>IMALI · ADMIN OPERATIONS</small><h1>Opportunity Control Center</h1><p>Safe preparation runs automatically. You control external action.</p></div><button onClick={refresh} disabled={busy}>Refresh</button></header>
  {error&&<div role="alert" className="oe-error">{error}</div>}{notice&&<div role="status" className="oe-notice">{notice}</div>}
  {!summary?<p>Loading aggregate database state…</p>:<>
  <div className="oe-kpis">{[['total','Total opportunities'],['AUTO_PROCESSING','Auto processing'],['ACTION_REQUIRED','Action required'],['BLOCKED_EXTERNAL','Blocked'],['DISPOSED','Disposed'],['COMPLETED','Completed'],['won','Won'],['actual_revenue','Actual revenue']].map(([key,title])=><button key={key} className={'oe-kpi '+(key==='ACTION_REQUIRED'?'oe-focus':'')} onClick={()=>select({metric:key})}><span>{title}</span><strong>{key==='actual_revenue'?money(c.actual_revenue_amount):number(c[key])}</strong><small>View records ↗</small></button>)}</div>
  <button className="oe-potential" onClick={()=>select({metric:'estimated_pipeline'})}><span>Estimated pipeline · <b>POTENTIAL — NOT EARNED</b></span><strong>{money(c.estimated_pipeline_amount)}</strong></button>
  <section className="oe-inbox"><div className="oe-section-head"><h2>Action required <span>{number(c.ACTION_REQUIRED)}</span></h2><small>Final decisions and documented ambiguities</small></div><div className="oe-lanes">{lanes.slice(1).map(l=><button key={l} onClick={()=>select({metric:'ACTION_REQUIRED',lane:l})}><span>{l}</span><b>{number(count('action_required',l))}</b></button>)}</div><button className="oe-approval-link" onClick={()=>select({metric:'commercial_final_approvals'})}>{number(c.commercial_final_approvals)} commercial messages ready for final approval →</button></section>
  <section id="engine-records" className="oe-records">
   <div className="oe-section-head"><h2>{filter.metric?label(filter.metric):filter.workbench_stage||filter.provider_stage||label(filter.operational_state)||'Records'}</h2><span>{number(records.total)} matching · {records.items.length} displayed</span></div>
   <nav className="oe-tabs" aria-label="Opportunity lanes">{lanes.map(l=><button className={selectedLane===l?'active':''} key={l} onClick={()=>select({...filter,lane:l==='ALL'?undefined:l,exclude_employment:undefined})}>{l}</button>)}</nav>
   <div className="oe-search"><input aria-label="Search opportunities" placeholder="Search company, title, or ID" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/><select aria-label="Operational state" value={filter.metric||''} onChange={e=>select({metric:e.target.value||undefined,lane:filter.lane})}><option value="">All states</option>{['AUTO_PROCESSING','ACTION_REQUIRED','BLOCKED_EXTERNAL','DISPOSED','COMPLETED'].map(s=><option key={s}>{s}</option>)}</select></div>
   {filter.exclude_employment&&<small>Business decisions first. Select Employment or ALL to include employment decisions.</small>}
   {busy&&<small role="status">Updating…</small>}
   <div className="oe-record-list">{!records.items.length&&!busy?<p className="oe-empty">No records match this view.</p>:records.items.map(r=><button className="oe-row" key={r.id} onClick={()=>open(r.id)}><div><strong>{r.company||'Unknown organization'}</strong><span className={'oe-badge '+r.operational_state}>{label(r.operational_state)}</span></div><p>{r.title}</p><div className="oe-row-meta"><span>{r.lane} · #{r.id}</span><span>{r.estimated_revenue?money(r.estimated_revenue)+' potential':'Value unknown'}</span>{(r.solicitation_due_at||r.procurement_deadline)&&<span>Due {when(r.solicitation_due_at||r.procurement_deadline)}</span>}</div><small>{r.next_human_action||r.blocker_reason||(r.next_machine_action?label(r.next_machine_action):null)||r.disposition_reason||r.completion_type}</small>{r.next_retry_at&&r.operational_state!=='ACTION_REQUIRED'&&<small>Next scheduled: {when(r.next_retry_at)}</small>}</button>)}</div>
   <div className="oe-pagination"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-10))}>Previous</button><span>{records.total?offset+1:0}–{Math.min(offset+10,records.total)} of {number(records.total)}</span><button disabled={offset+10>=records.total} onClick={()=>setOffset(offset+10)}>Next</button></div>
  </section>
  <details className="oe-section" open><summary>Autopilot working <span>{number(c.AUTO_PROCESSING)}</span></summary><div className="oe-chips">{['target_resolution','contact_discovery','verification','retry_backoff','procurement_research','outreach_preparation','provider_research','reward_research','recovery_research',...new Set((groups.autopilot||[]).map(g=>g.label))].filter((v,i,a)=>a.indexOf(v)===i).map(a=><button key={a} onClick={()=>select(a==='retry_backoff'?{metric:'retry_backoff'}:{operational_state:'AUTO_PROCESSING',next_machine_action:a})}>{label(a)} <b>{number(a==='retry_backoff'?c.retry_backoff:count('autopilot',a))}</b></button>)}</div><div className="oe-health">{['fast','slow'].map(l=>{const cycle=summary.cycles?.find(x=>x.lane===l);return <div key={l}><b>Last {l} cycle</b><span>{when(cycle?.started_at)}</span><span>{cycle?.result||'Not recorded'} · {cycle?.runtime_seconds||'—'}s · guard {cycle?.guard_status||'unknown'}</span></div>;})}{health?.timers?.map(t=><div key={t.unit}><b>{t.unit.replace('imali-opportunity-','')}</b><span>{t.ActiveState} · {t.UnitFileState}</span><span>Next: {t.next_scheduled||t.NextElapseUSecRealtime||'Not scheduled'}</span></div>)}</div><p className="oe-muted">Preparation only. External execution requires your explicit authorization.</p></details>
  <details className="oe-section"><summary>Blocked externally <span>{number(c.BLOCKED_EXTERNAL)}</span></summary><div className="oe-chips">{(groups.blocked||[]).map(g=><button key={g.label} onClick={()=>select({operational_state:'BLOCKED_EXTERNAL',blocker_type:g.label})}>{label(g.label)} <b>{number(g.count)}</b></button>)}</div></details>
  <details className="oe-section"><summary>Government workbench</summary><div className="oe-chips">{stages.map(s=><button key={s} onClick={()=>select({government_only:'1',workbench_stage:s})}>{s} <b>{number(count('government',s))}</b></button>)}</div></details>
  <details className="oe-section"><summary>Subcontractor workbench <span>{number(c.managed_delivery)} managed delivery</span></summary><p>{number(summary.candidates?.total)} candidate records across {number(c.provider_candidates_found)} opportunities. Candidate evidence does not imply selection or a commitment.</p><div className="oe-chips">{providerStages.map(s=><button key={s} onClick={()=>select({provider_stage:s,exclude_terminal:'1'})}>{s} <b>{number(count('subcontractor',s))}</b></button>)}<button onClick={()=>select({metric:'provider_candidates_found'})}>Opportunities with candidates <b>{number(c.provider_candidates_found)}</b></button></div></details>
  <details className="oe-section"><summary>Disposed <span>{number(c.DISPOSED)}</span></summary><div className="oe-chips">{(groups.disposed||[]).map(g=><button key={g.label} onClick={()=>select({operational_state:'DISPOSED',disposition_reason:g.label})}>{label(g.label)} <b>{number(g.count)}</b></button>)}</div></details>
  <details className="oe-section" open><summary>Actual external results</summary><div className="oe-chips">{[['commercial_sent','Commercial sent'],['applications_submitted','Applications submitted'],['bids_submitted','Bids submitted'],['reward_submissions','Reward submissions'],['won','Won'],['actual_revenue','Revenue records']].map(([k,l])=><button key={k} onClick={()=>select({metric:k})}>{l} <b>{number(c[k])}</b></button>)}</div></details>
  <details className="oe-section"><summary>Recovery compliance <span>{summary.recovery?.compliance_locked} locked jurisdictions</span></summary><p>Authoritative compliance approval is required. No owner outreach, claims, or fees are authorized.</p><div className="oe-chips"><button onClick={()=>jurisdictions()}>Jurisdictions {summary.recovery?.jurisdictions}</button><button onClick={()=>jurisdictions('verified')}>Verified {summary.recovery?.verified}</button><button onClick={()=>jurisdictions('compliance_locked')}>Compliance locked {summary.recovery?.compliance_locked}</button><button onClick={()=>select({lane:'Recovery'})}>Cases {summary.recovery?.cases}</button></div>{recovery&&recovery.map(r=><article className="oe-row" key={r.jurisdiction}><strong>{r.jurisdiction}</strong><p>{r.reviewer_status}</p><Source url={r.source_url}/><small>{r.notes}</small></article>)}</details>
  <details className="oe-section"><summary>System safety &amp; cycle health</summary><div className="oe-health">{health?.services?.map(s=><div key={s.unit}><b>{s.unit}</b><span>{s.ActiveState} · {s.SubState} · {s.UnitFileState}</span></div>)}<div><b>Disk · resource guard {health?.resource_guard?.status||'unknown'}</b><span>{health?.disk||'Unknown'}</span></div><div><b>Outbound safety flags</b><pre>{JSON.stringify(health?.outbound||{},null,2)}</pre></div></div></details>
  <footer className="oe-muted">Database aggregates · updated {when(summary.as_of)} · all counts open their records.</footer>
  </>}
  {detail&&<div className="oe-overlay" role="dialog" aria-modal="true" aria-label="Opportunity detail"><article className="oe-detail"><header><div><small>#{detail.item.id} · {detail.item.lane}</small><h2>{detail.item.company}</h2></div><button onClick={()=>setDetail(null)} aria-label="Close detail">Close ×</button></header><h3>{detail.item.title}</h3><p className="oe-badge">{label(detail.item.operational_state)}</p><p>{detail.item.next_human_action||detail.item.blocker_reason||label(detail.item.next_machine_action)}</p><Source url={detail.item.url}/><dl>{[['Revenue path',detail.item.revenue_path],['Estimated value (potential)',money(detail.item.estimated_revenue)],['Official target',detail.item.contact_url||detail.item.application_url],['Contact',detail.item.outreach_contact_email],['Fit rationale',detail.item.business_reason],['Verification evidence',detail.item.execution_source_reason||detail.item.execution_reason],['Eligibility',detail.item.eligibility_reason],['Deadline',when(detail.item.solicitation_due_at||detail.item.procurement_deadline)],['Next retry',when(detail.item.next_retry_at)],['Disposition',detail.item.disposition_reason],['Disposed',detail.item.disposed_at?when(detail.item.disposed_at):null]].filter(x=>x[1]).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl>
   {detail.item.outreach_body&&<section><h3>Prepared commercial response</h3><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea rows={9} value={message} onChange={e=>setMessage(e.target.value)}/></label>{detail.item.operational_state==='ACTION_REQUIRED'&&<button onClick={()=>decision('edit')} disabled={busy}>Save edits</button>}</section>}
   {detail.providers?.length>0&&<section><h3>Provider candidates</h3>{detail.providers.map(p=><div className="oe-row" key={p.id}><strong>{p.name}</strong><p>{p.verification_status} · {p.decision||'Not selected'}</p><Source url={p.website}/><pre>{JSON.stringify({evidence:p.evidence,economics:p.economics},null,2)}</pre>{detail.item.final_approval_type==='PROVIDER_SELECTION'&&p.verification_status==='verified'&&<button onClick={()=>decision('provider_approve',{provider_id:p.id})}>Approve candidate</button>}</div>)}</section>}
   {detail.research?.length>0&&<details open><summary>Official procurement evidence &amp; requirements</summary><pre>{JSON.stringify(detail.research,null,2)}</pre></details>}
   {detail.reward?.length>0&&<details><summary>Reward research and safeguards</summary><pre>{JSON.stringify(detail.reward,null,2)}</pre></details>}
   <label>Decision evidence / rejection reason<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the evidence supporting your decision"/></label>
   <div className="oe-actions">{detail.item.operational_state==='BLOCKED_EXTERNAL'&&<button disabled={busy||!note.trim()} onClick={()=>decision('dependency_resolved')}>Dependency resolved — recheck</button>}{detail.item.blocker_type==='REGISTRATION_REQUIRED'&&<button disabled={busy||!note.trim()} onClick={()=>decision('registration_confirm')}>Confirm official registration</button>}{detail.item.final_approval_type==='GOVERNMENT_PACKAGE_DOCUMENTS'&&<button disabled={busy||!note.trim()} onClick={()=>decision('package_confirm')}>Confirm required documents</button>}{detail.item.operational_state==='ACTION_REQUIRED'&&['COMMERCIAL_OUTREACH','GOVERNMENT_BID','EMPLOYMENT_APPLICATION','REWARD_ENTRY','REWARD_SUBMISSION'].includes(detail.item.final_approval_type)&&<button className="oe-approve" disabled={busy} onClick={()=>decision('approve')}>Approve preparation</button>}{['GOVERNMENT_ELIGIBILITY','ELIGIBILITY'].includes(detail.item.final_approval_type)&&<button disabled={busy||!note.trim()} onClick={()=>decision('eligibility_confirm')}>Confirm eligibility with evidence</button>}{['DISPOSED','BLOCKED_EXTERNAL'].includes(detail.item.operational_state)&&<button disabled={busy} onClick={()=>decision('restore')}>Restore / reopen</button>}{!['DISPOSED','COMPLETED'].includes(detail.item.operational_state)&&<button disabled={busy||!note.trim()} onClick={()=>decision('dispose')}>Reject / dispose</button>}</div><small>Approval and sending are separate. These controls do not perform an external action.</small>
   <details><summary>Preparation attempts &amp; transition audit</summary><pre>{JSON.stringify({attempts:detail.attempts,history:detail.history},null,2)}</pre></details></article></div>}
 </main>;
}
